---
- name: Wipe all packages by nvidia
  ansible.builtin.apt:
    name:
      - "*cuda*"
      - "*cublas*"
      - "*cufft*"
      - "*cufile*"
      - "*curand*"
      - "*cusolver*"
      - "*cusparse*"
      - "*gds-tools*"
      - "*npp*"
      - "*nvjpeg*"
      - "nsight*"
      - "*nvidia*"
      - "datacenter-gpu-manager"
    state: absent
    purge: true
    autoremove: true
  notify:
    - Reboot

- name: Blacklist the nouveau driver
  ansible.builtin.copy:
    src: blacklist-nouveau.conf
    dest: /etc/modprobe.d/blacklist-nouveau.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Update initramfs
    - Reboot

- name: Load the VFIO kernel module during boot
  ansible.builtin.copy:
    src: vfio-modules.conf
    dest: /etc/modules-load.d/vfio.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Update initramfs
    - Reboot

- name: Enable IOMMU passthrough mode
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="quiet"$'
    line: "GRUB_CMDLINE_LINUX_DEFAULT=\"quiet iommu=pt\""
    owner: root
    group: root
    mode: 0644
    state: present
  notify:
    - Update grub
    - Reboot
